spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/login
        - id: guards-route
          uri: lb://GUARDS-SERVICE
          predicates:
            - Path=/absence/**,/teachingHours/**,/document/**
          filters:
            - name: AuthenticationFilter

    endpoints:
      web:
        exposure:
          include: "*"

    endpoint:
      health:
        show-details: always
      gateway:
        enabled: true

server:
  port: 8090

privateKey: ZnJhc2VzbGFyZ2FzcGFyYWNvbG9jYXJjb21vY2xhdmVlbnVucHJvamVjdG9kZWVtZXBsb3BhcmFqd3Rjb25zcHJpbmdzZWN1cml0eQ==bWlwcnVlYmFkZWVqbXBsb3BhcmFiYXNlNjQ=

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
